[package]
name = "kierancli"
version = "0.2.2"
edition = "2021"
authors = ["Kieran Crossland <kierancrossland1st@gmail.com>"] 
repository = "https://github.com/kierancrossland/kierancli/"
readme = "README.md"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"
git2 = "0.14.4"
