[package]
name = "kierancli"
version = "0.4.0"
edition = "2021"
authors = ["Kieran Crossland <kierancrossland1st@gmail.com>"] 
repository = "https://github.com/kierancrossland/kierancli/"
readme = "README.md"
license = "AGPL-3.0"
keywords = ["unix", "shell, linux, bsd, bash, macos, rust-lang"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"
git2 = "0.14.4"
open = "3.0.1"