[package]
name = "kierancli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"
git2 = "0.14.4"
dirs = "4.0.0"